# Generated by Django 5.1.7 on 2025-03-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='스포츠 종목')),
                ('content', models.TextField(verbose_name='스포츠 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
